# Generated by Django 4.2.30 on 2026-06-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('pseudonym', models.CharField(max_length=50)),
                ('is_image_signature', models.BooleanField(default=False)),
                ('is_text_signature', models.BooleanField(default=False)),
            ],
        ),
    ]
